'use client'

import { useState } from 'react';
import { ModeToggle } from '@/components/mode-toggle';
import dynamic from 'next/dynamic';
import { GradientTop } from '@/components/gradientTop';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { FileQuestionIcon, StarIcon } from 'lucide-react';
import { Separator } from '@/components/ui/separator';
const SymptomFormMain = dynamic(() => import('./_components/symptom-form-main'), { ssr: false });

export default function SymptomSearchPage() {

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  return (
    <section className="relative overflow-x-hidden flex flex-col font-inter min-h-svh">
      <div className="w-full px-[1.15rem] py-8 lg:px-8 lg:py-10">
        <header className='relative flex items-center lg:mb-10 space-y-8'>
          <h1 className="shadow-heading text-4xl sm:text-5xl md:text-6xl my-4">Symptom Analyzer</h1>
        </header>
        <section className='flex flex-col lg:flex-row gap-4 lg:items-start lg:justify-between'>
          <main className='lg:max-w-6xl mx-auto border rounded-lg p-2 lg:p-6 bg-[#ddd2] dark:bg-[#2222] backdrop-blur-lg'>
            <SymptomFormMain />
          </main>
          <section className="p-6 bg-[#eee2] dark:bg-[#2222] shadow rounded-lg w-full lg:w-1/2 border">
            <div className="flex items-center gap-2 mb-4">
              <FileQuestionIcon className="w-6 h-6" />
              <h1 className="text-3xl font-bold">FAQs</h1>
            </div>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1" className='font-bold border-b-light-pink'>
                <AccordionTrigger className='font-semibold text-sm md:text-base'>Disclaimer</AccordionTrigger>
                <AccordionContent className='text-xs font-medium pb-2 inline-block'>
                  <p>This information is generated by an AI and is not a substitute for professional medical advice.  Always consult with a qualified healthcare provider for any health concerns.</p>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </section>
        </section>
      </div>
    </section>
  );
}